@echo off
echo Starting CampusInsight AI Full-Stack System...
echo 1. Launching Backend FastAPI Server (Port 8000)...
start "CampusInsight Backend" cmd /k "cd /d %~dp0backend && .\venv\Scripts\python.exe run.py"
echo 2. Launching Frontend Dev Server (Port 5173)...
start "CampusInsight Frontend" cmd /k "cd /d %~dp0frontend && npm run dev"
echo.
echo CampusInsight AI backend and frontend servers are now running!
